### ISSUE TITLE
Some Doubts about Stage1

### ISSUE THREAD

**Issue by rubenssoto** [awslabs/aws-serverless-data-lake-framework#5]
Hello Guys,

First of All, congratulations for this great architecture.

I have some doubts about the first part.

When lambda calls Stage1, Are parameters passed to Steps Functions, like file paths etc?? 
The step functions stage1, Insert new files information in dynamodb, what is this information is used for?
The Light transformation get information about files where? In dynamo?

Thank you.

**Comment by josecw** [comment]
Hope we can have a webinar session on this great framework.

**Comment by jaidisido** [comment]
Thanks for your comment @rubenssoto. Did you have a look at the information on this [page](https://sdlf.readthedocs.io/en/latest/architecture.html) by any chance?

In short, the entire process is event-driven. It starts with the generation of an S3 event when a file lands in the bucket. That event is a JSON document with metadata about the S3 object (e.g. timestamp, path...), and this information is passed along to subsequent components including StageA. You can check the exact parameters passed into the Step Functions by looking at their input in the console.

In regards to metadata, we log every change to the S3 objects (Create, Update, Delete) as well as details about the pipelines processing those objects in DynamoDB tables. This information is usually leverage for a number of purposes, including:

- Monitoring: Determining which pipelines have succeeded/failed and for which files
- Tagging and lifecycle policies: You can add business metadata alongside operational metadata to each entry in the tables in order to tag S3 objects or apply life cycle policies on them

Let me know if this covers your questions.

@josecw, glad to hear you find the framework useful. We are in the processing of recording videos for it so stay tuned!

**Comment by rubenssoto** [comment]
@jaidisido thank you so much for your answer.

Do you process each file at a time or process all files for that specific dataset? If I understand right a dataset could be a group of many tables. I'm asking because I have a chance to create one pipeline with spark and processing different tables in different spark jobs was not efficient, it was much better processing many tables in the same spark job using threads for each table.

In foundations, specific in lambda route, you get info about s3 event and send to the next queue s3 event data with team and dataset tag, probably to know that event belongs to the same group of files.

In stage A routing, you get the information from the last queue and send to State machine only this
event_body['team'],
event_body['pipeline'],
event_body['pipeline_stage']

and in stage-a-preupdate-metadata you get the State machines parameters  and start the job to process the files

octagon_client.start_pipeline_execution(
            pipeline_name='{}-{}-stage-{}'.format(object_metadata['team'],
                                                  object_metadata['pipeline'],
                                                  stage[-1].lower()),
            dataset_name='{}-{}'.format(
                object_metadata['team'], object_metadata['dataset']),
            comment=event
        )

you send only information about team, pipeline and dataset, how you get the file's metadata to know with files you have to process?


Sorry for too many questions, but we are making something very similar to your framework, and your experience will help us a lot!

**Comment by jaidisido** [comment]
In the first stage of an SDLF pipeline (StageA), each file is processed individually. Then in the second stage (StageB), a batch of files is processed using an AWS analytical service (E.g. Glue job/workflow, EMR step, Fargate task...). This is the default example in the framework as it is a common pattern for many use cases, but you can modify the templates to adapt the orchestration to a different pattern if need be. I do recommend using the same Spark job to process multiple tables as it is more efficient.

Regarding your second question, there is a DynamoDB table called `octagon-Dataset-dev` where we store metadata about each dataset, including what transformation should be applied on incoming files belonging to a given team/pipeline/dataset. For instance:
```
{
    "name": "engineering-legislators",
    "pipeline": "main",
    "transforms": {
        "stage_a_transform": "light_transform_blueprint",
        "stage_b_transform": "heavy_transform_blueprint"
    },
    "":
    "max_items_process": {
        "stage_b": 100,
        "stage_c": 100
    },
    "min_items_process": {
        "stage_b": 1,
        "stage_c": 1
    },
    "classification": "Public",
    "description": "US Legislators Data",
    "frequency": "DAILY",
    "owner": "Every Politician",
    "owner_contact": "politician@whitehouse.org",
    "tags": [
        {
        "key": "cost",
        "value": "parliament division"
        }
    ],
    "type": "TRANSACTIONAL",
    "version": 1
}
```
The `transforms` section in the DynamoDB entry above specifies the python files that should be used when transforming a given dataset, in a given pipeline and team. Those python transformations would have previously been pushed to a CodeCommit repository (`sdlf-datalakeLibrary`) and attached to the Lambdas in the pipeline as a Lambda Layer. The biggest advantage of this approach is that dataset transformations are completely decoupled from the pipeline (i.e. you can run more than one dataset in the same pipeline).

We go into detailed explanations about this in this section of the workshop:
https://sdlf.workshop.aws/10-deployment/600-transformations.html

**Comment by jaidisido** [comment]
Feel free to open a new issue if any more questions
